global_args:
  framework: 'torch'
  device: 'cuda'
  output_path: /home/michal/Desktop/Data/forestry/PointPillars/Custom/
  box_params_num: 9
  model_dim: 3
  seed: 0
  
dataset:
  name: razenbach
  dataset_path: /home/michal/Desktop/Data/forestry/NumpyData_OD/razenbach/

model:
  name: PointPillars
  point_cloud_range: [0, 0, 0, 40.0, 40.0, 30.0]
  
  classes: ['Tree']
  #input_features: [0,1,2,3,4]
  input_features: [0,1,2,3]

  loss:
    focal:
      gamma: 2.0
      alpha: 0.25
      loss_weight: 1.0
    smooth_l1:
      beta: 0.11
      loss_weight: 2.0
    cross_entropy:
      loss_weight: 0.2

  voxelize:
    max_voxel_points: 50
    voxel_size: &vsize
      [0.1, 0.1, 0.3]
    max_voxels: 7500000

  voxel_encoder:
    in_channels: 4
    feat_channels: [20]
    voxel_size: *vsize

  vertical_encoder:
    in_channels: 20
    out_channels: [20, 32, 64, 128, 196]

  backbone:
    in_channels: 392
    out_channels: [196, 128, 128]
    layer_nums: [1, 1, 1]
    layer_strides: [2, 2, 2]

  neck:
    in_channels: [512, 256, 128]
    out_channels: [256, 256, 256]
    upsample_strides: [1, 2, 4]
    use_conv_for_no_stride: false

  head:
    in_channels: 128
    nms_pre: 500
    nms_thresh: 0.00001
    score_thr: 0.3
    ranges: [[0, 0, 0, 40.0, 40.0, 30.0]]
    sizes: [[0.75, 0.75, 12],[1.3, 1.3, 17], [1.0, 1.75, 20]]
    rotations: [[0.0, 0.0, 0.0], [0.0, 0.0, 1.57],[0.3142, 0.0, 0.0],[-0.3142, 0.0, 0.0],]
    iou_thr: [[0.08, 0.2]]

  augment:
    PointShuffle: True
    #ObjectRangeFilter:
    #  point_cloud_range: [0, 0, 0, 40.0, 40.0, 30.0]

  preprocess:

    voxelization:
      voxel_size: [0.03, 0.03, 0.03]
      max_voxel_points: 15
      reflectance_sampling: True

    featurizer:
      normal_rad: 0.1 
      normal_max_nn: 50
      fpfh_rad: 0.1
      fpfh_max_nn: 50

    filter:
      path: '/home/michal/Desktop/Dev/forestry/PointPillars/model/models/'
      filter_type: 'xgboost' 
      mlp:
        device: 'cuda'
        classes: {0: 'background', 1: 'foreground'}
        input_channels: 37
        trunk_confidence: 0.5
      xgboost:
        trunk_confidence: 0.75

pipeline:
  name: ObjectDetection
  inference_mode: False
  is_resume: False
  resume_from: '2023-07-10-11-55-18'
  training_batch_size: 1
  validation_batch_size: 1
  testing_batch_size: 1
  save_ckpt_freq: 5
  max_epoch: 20
  grad_clip_norm: 2
  num_workers: 4
  pin_memory: false
  validation_freq: 1

  optimizer:
    lr: 0.0001
    betas: [0.95, 0.99]
    weight_decay: 0.01

  # evaluation properties
  overlaps: [0.1]